# Generated by Django 5.2.6 on 2026-07-15 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0002_schooltenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HQNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('notice_type', models.CharField(choices=[('performance_warning', 'Performance Warning'), ('compliance', 'Compliance Notice'), ('general', 'General Notice'), ('urgent', 'Urgent Notice')], default='general', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_deadline', models.DateField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_notices', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_notices', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hq_notices', to='tenants.schooltenant')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=20)),
                ('total_students', models.IntegerField(default=0)),
                ('average_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject_performance', models.JSONField(default=dict)),
                ('average_attendance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('scholarship_participation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('scholarship_success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='tenants.schooltenant')),
            ],
            options={
                'ordering': ['-academic_year', '-term'],
                'unique_together': {('school', 'academic_year', 'term')},
            },
        ),
    ]
